name: call_app_livekit
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_webrtc: ^0.12.1+hotfix.1
  livekit_client: ^2.3.4
  socket_io_client: ^3.0.0
  go_router: ^14.6.1
  provider: ^6.1.2
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
